### ISSUE TITLE
failed to refresh

### ISSUE THREAD

**Issue by lolren** [nab138/Ez-AltServer-Linux#1] opened 2022-10-18 12:31 UTC
Hi. Thank you for the work. However, I am getting this problem: 

>Failed to handle request:AltServer could not find the dSent Bytes Count: 86 (86)
Sent Data: 86 Bytes
evice.
Failed to handle request:AltServer could not find the dSent Bytes Count: 86 (86),
<

**Comment by nab138** [comment] 2022-10-19 14:47
From the looks of it, your error is trying to say altserver could not find the device. This is more of a question related to the AltServer-Linux repo, but I can try to help you here. Also know that in a couple days I am going to release a properly packaged and updated version so you could try again then.

How are you communicating with the device? Are you using a usb cable or netmuxd? If netmuxd, how are you starting it?

**Comment by lolren** [comment] 2022-10-20 18:19
Hi. Thank you for the reply, and sorry for my late reply, I am on holiday at the moment, afk. It does that with both the cable and wifi, after it tries to refresh the app.  The message on the phone is : "could not find altserver"

**Comment by nab138** [comment] 2022-10-21 01:29
I'm not super versed in the protocols used by AltServer so I'm going to refer you to issue [#49](https://github.com/NyaMisty/AltServer-Linux/issues/49) where you hopefully can find some more issues. From what I gathered, you will need to ensure that for the first time, you aren't using netmuxd and the output of `ideviceinstaller -l` is actually your installed apps. If it isn't, the issue isn't with altserver.

Note: It seems the user in that issue solved the problem, and has a different error about their apple id, which is fixed with this software as it uses anisette_server. If you can get to that point, it should work.

**Comment by lolren** [comment] 2022-10-21 10:45
Tried all the commands on the solution page, but none of them list anything. (ideviceinstaller -l, idevicepair etc). I am currently running kde neon, which runs Ubuntu 20.04, which may have an outdated libimobiledevice package. will try to upgrade when I get some more time. Thank you for your help.

**Comment by nab138** [comment] 2022-10-21 12:24
Feel free to post here if you solve this. Hopefully, upgrading libimobiledevice should fix it. The only other thing I can thing I can think of is seeing if you can get any reasonable output from `idevice_id -l` and `ideviceinfo`. If not, maybe try a different usb cable. 

If you’ve tried all this and still can’t fix it leave a comment on the issue I mentioned before (or potentially open a new one, it sounds like it could be a different problem) and hopefully you can get help there.

Closing because the issue isn’t with this project, it is with altserver Linux or libimobiledevice

**Closed as completed by nab138** 2022-10-21 12:24 UTC

**Comment by lolren** [comment] 2022-10-21 18:28
Thank you for the response and help. I have upgraded to ubuntu 22.04, and I got the error:"No device found". Nothing helped until I restarted usbmuxd service with : "systemctl restart usbmuxd.service" and then : "idevicepair pair". After that, everything is ok. To help people in my situation, you can look for the version of Usbmuxd and warn about this in the script. also, have an option to restart and pair via a button maybe. Have a lovely day :D

**Comment by lolren** [comment] 2022-10-21 21:05
I get an error when I try to install Altstore from the app:
`Starting notification connection to device: Loren’s iPhone
*** WARNING *** The program 'python3.10' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
DNSServiceRegister result: 0
./AltServer --udid 00008030-000C0CDC0100802E -a user@icloud.com -p  pass 1_5.ipa
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/lolren/Desktop/Ez-AltServer-Linux-main/main.py", line 99, in <lambda>
    button = Button(top, text="Ok", command=lambda:runInstall(top, email.get(), password.get(), udid))
  File "/home/lolren/Desktop/Ez-AltServer-Linux-main/main.py", line 71, in runInstall
    subprocess.Popen.kill(alt_proc)
UnboundLocalError: local variable 'alt_proc' referenced before assignment
` Also, can the script check if Usbmuxd is running? I have to restart it all the time, and think that other will get the same error

**Comment by nab138** [comment] 2022-10-21 22:26
I will sort out the altstore issue and I’ll try to add usbmuxd detection and the pair/restart button when I release the fully packaged version. I’ve never had an issue with usbmuxd but I will try to fix it. Thank you for the feedback!

The release might be a bit delayed because I’m trying to sort out a weird issue with pystray where the tray icon won’t disappear and you can only use it the first time you close the app.

**Comment by lolren** [comment] 2022-10-22 07:24
That is awesome. Linux is my OS of choice and I booted Windows just for Alserver. Before I have seen your program, I wanted to do the same in Bash, as is the only scripting language I know. Now you did it better than I would do it. Also, another feature would be " Save the username/password" tickbox, maybe with a warning that they are saved in plaintext, because a lot of people just have 1 phone and won`t care about the security side of things. Keep up the good work and looking forward to use the final version :D
